enum ErrorCode {
    ERROR_UNABLE_TO_OPEN_FILE = 100,
    ERROR_CONSOLE_NOT_ALLOWED_UNLESS_IN_DEBUG = 200,
    ERROR_UNABLE_TO_WRITE_TO_SOCKET = 300,
    ERROR_CODE_ONLY_ONE_ERROR_DETECTION_MODE_ALLOWED = 400,
    ERROR_UNKNOWN_PARAMETER = 500,
};
